import * as t from "io-ts";

/** This is the list of 1Password category types */
export const CategoryUuid = t.union([
  t.literal("001"),
  t.literal("002"),
  t.literal("003"),
  t.literal("004"),
  t.literal("005"),
  t.literal("006"),
  t.literal("100"),
  t.literal("101"),
  t.literal("102"),
  t.literal("103"),
  t.literal("104"),
  t.literal("105"),
  t.literal("106"),
  t.literal("107"),
  t.literal("108"),
  t.literal("109"),
  t.literal("110"),
  t.literal("111"),
  t.literal("112"),
  t.literal("113"),
  t.literal("114"),
  t.literal("115"),
]);

export const CategoryReadable = t.union([
  t.literal("login"),
  t.literal("credit-card"),
  t.literal("secure-note"),
  t.literal("identity"),
  t.literal("password"),
  t.literal("document"),
  t.literal("software-license"),
  t.literal("bank-account"),
  t.literal("database"),
  t.literal("driver-license"),
  t.literal("outdoor-license"),
  t.literal("membership"),
  t.literal("passport"),
  t.literal("reward-program"),
  t.literal("ssn"),
  t.literal("wireless-router"),
  t.literal("server"),
  t.literal("email"),
  t.literal("api-credential"),
  t.literal("medical-record"),
  t.literal("ssh"),
  t.literal("crypto-wallet"),
]);

export const CategoryUuidDictionary: Record<
  t.TypeOf<typeof CategoryReadable>,
  t.TypeOf<typeof CategoryUuid>
> = {
  login: "001",
  "credit-card": "002",
  "secure-note": "003",
  identity: "004",
  password: "005",
  document: "006",
  "software-license": "100",
  "bank-account": "101",
  database: "102",
  "driver-license": "103",
  "outdoor-license": "104",
  membership: "105",
  passport: "106",
  "reward-program": "107",
  ssn: "108",
  "wireless-router": "109",
  server: "110",
  email: "111",
  "api-credential": "112",
  "medical-record": "113",
  ssh: "114",
  "crypto-wallet": "115",
};
